name: Smoke Test
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to run smoke test against'
        required:    true

jobs:
  perform-smoke-test:
    env:
      IMAGE_NAME: shuttlerock/smoke-test
      BOT_USER: sr-devops
    runs-on: ubuntu-latest

    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: Smoke test on ${{ github.event.inputs.environment }} ${{ job.status }}
          author_name: Smoke Test
          fields: repo,took
          mention: here
          if_mention: always
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
